In [1]:
#1. Import NumPy using `import numpy as np` and print the NumPy version.
import numpy as np
print(np.__version__)

2.2.3


In [5]:
#2. Create a 1D NumPy array from the list `[1, 2, 3, 4, 5]` and print it.
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

[1 2 3 4 5]


In [6]:
#3. Create a 2D NumPy array from the list `[[1, 2, 3], [4, 5, 6]]` and print its shape.
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.shape)

(2, 3)


In [7]:
#4. Use `np.zeros()` to create a 3x3 array of zeros and print the array.
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#5. Create a 2x2 array of ones using `np.ones()` and print the result.
ones_array = np.ones((2, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]]


In [9]:
#6. Generate an array of numbers from `1` to `9` with a step of `2` using `np.arange()` and print it.
range_array = np.arange(1, 10, 2) 
print(range_array)

[1 3 5 7 9]


In [10]:
#7. Reshape a 1D array of 6 elements into a 2x3 array using the `reshape()` method and print the reshaped array.
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3) 
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [11]:
#8. Slice a NumPy array `[10, 20, 30, 40, 50]` to extract elements from index 1 to 3 and print the slice.
arr = np.array([10, 20, 30, 40, 50])
sliced_arr = arr[1:4]  
print(sliced_arr)

[20 30 40]


In [12]:
#9. Perform element-wise addition of two arrays `[1, 2, 3]` and `[4, 5, 6]` using NumPy and print the result.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2 
print(sum_arr)

[5 7 9]


In [13]:
#10. Use `np.random.rand(3,3)` to generate a random 3x3 matrix and print it.
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.16650737 0.78886273 0.13251662]
 [0.80246197 0.8029237  0.33862632]
 [0.60435571 0.75955032 0.20180824]]
